name: IOS-MCN-RAN Issue Template
description: Issues cannot be submitted without selecting at least one mandatory label.
title: "\u200B"
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Fill out all required fields below.

  - type: textarea
    id: issue_details
    attributes:
      label: Issue Details
      description: "Please fill out the template below with your issue details."
      value: |
        **Issue/Feature Description:**

        **Why this issue to fixed / feature is needed (give scenarios or use cases):**

        **How to reproduce, in case of a bug:**

        **Other Notes / Environment Information:**

  - type: markdown
    attributes:
      value: |
        ---
        ## Label Selection
        Please select the appropriate labels for this issue.

  - type: dropdown
    id: mandatory_category
    attributes:
      label: Label
      description: "MUST select one of the following categories for the issue."
      options: 
        - ""
        - "UNI"
        - "DIST"
        - "UNI-DIST-COMMON"
      multiple: false
    validations:
      required: true

  - type: dropdown
    id: additional_labels
    attributes:
      label: Additional Labels (Optional)
      description: "Select any additional relevant labels for the issue."
      options:
          - "bug"
          - "DIST"
          - "documentation"
          - "duplicate"
          - "enhancement"
          - "good first issue"
          - "help wanted"
          - "invalid"
          - "question"
          - "UNI"
          - "UNI-DIST-COMMON"
          - "wontfix"
      multiple: true
    validations:
      required: false
